List<String> getLyrics() {
  return [
    'I need it all downtown, nigga',
    'Put it back where you fuckin\' found it though',
    'I need it all down (my nigga)',
    'Keep \'em right there, oh, you found \'em though',
    'I want a shirt that make my body feel all sexy',
    'I want a chain that make my body feel all hefty',
    'I want my head to fall off when I walk out the door',
    'I want the rain to fall down and I\'m askin\' for more',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
    'I want a love that make me feel like I ain\'t breakin\' ya heart',
    'I wanna know what made you stay when it was wrong from the start',
    'I need to know where you went lookin\' where you went through the chop',
    'I need this fear of being everybody else to depart',
    'I got a lot on my mind, not enough hours to shed',
    'Not enough trust to believe, not enough feelin\' to care',
    'I\'m feeling numb to the world so I been ignoring instead',
    'I\'m seeing through what I want to recognise who is there, yeah',
    'Throw me in the fire, baby, I\'ll survive',
    'Coming top down by the seaside',
    'Ay-yi-yi-yi-yah',
    'Ay-yi-yi-yi-yah',
    'See the wrong side of the 45',
    'Only you and me by the borderline (ooo)',
    'Ay-yi-yi-yi-yah (ooo-ooo)',
    'Ay-yi-yi-yi-yah, let it go',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
    'I would show you off for everything I own',
    'I know it\'s not used to',
    'See they could tear me down, take everything I made',
    'I\'ll still be here next to you',
    'Throw me in the fire, baby, I\'ll survive',
    'Coming top down by the seaside',
    'Ay-yi-yi-yi-yah',
    'Ay-yi-yi-yi-yah',
    'See the wrong side of the 45',
    'Only you and me by the borderline (ooo)',
    'Ay-yi-yi-yi-yah (ooo-ooo)',
    'Ay-yi-yi-yi-yah, let it go',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
    'Ridin\' on the roof with a dollar sign',
    'Attached to my head, head, head, head, head, head, head, head (woo, slow)',
  ];
}
